"""
Component library — load ``components/components.json`` and build the runtime
structures from it (spec: ``spec/component-editor.md``).

The file is generated by ``tools/generate_components.py`` and holds, for every
CircuiTikZ-symbol kind, its registry + code-generation data (pins, bbox, leads,
metadata) plus a single ``origin_svg`` placement constant.  It replaces the
per-component magic numbers that used to live in ``registry.py``, the
``circuitikz`` codegen tables, and ``svgsym.py``.

The 33 SVG-symbol kinds live in the file; the 6 bespoke kinds (the resizable
annotations ``open``/``short`` and the drawing primitives) are not
command-derived and keep their hand-coded ``ComponentDef`` in ``registry.py``.

* :func:`library_component_defs` -> the registry ``ComponentDef``s (used by
  ``registry.py``).
* :func:`build_codegen_tables` -> the ``circuitikz`` classification + alignment
  tables (used by ``app/codegen/circuitikz.py``).
* :func:`origin_svg` -> the constant SVG point that maps to a symbol's origin
  pin (used by ``app/canvas/svgsym.py``).
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from app.components.model import Component, ComponentDef, PinDef
from app.resources import resource_path

# Kinds NOT in the library (no CircuiTikZ-command symbol) — keep hand-coded defs.
NON_LIBRARY_KINDS: frozenset[str] = frozenset(
    {"open", "short", "bipole", "rect", "circle", "text_node"}
)


def library_path() -> Path:
    return Path(resource_path("components", "components.json"))


@lru_cache(maxsize=1)
def _data() -> dict:
    return json.loads(library_path().read_text(encoding="utf-8"))


def load_library() -> dict[str, dict]:
    """The per-kind component records."""
    return _data()["components"]


def origin_svg() -> tuple[float, float]:
    """The constant SVG coordinate that every symbol's origin pin maps to.

    All symbols are rendered in a fixed bounding box with the origin pin at TeX
    (0,0), so this single point is the placement anchor for the canvas transform
    (``svgsym``) — there are no per-component anchors.
    """
    x, y = _data()["origin_svg"]
    return (float(x), float(y))


# ---------------------------------------------------------------------------
# Variants (per-instance boolean attributes, spec §5.4 / §7.4a)
# ---------------------------------------------------------------------------

def variant_specs(kind: str) -> list[dict]:
    """The boolean variants a *kind* declares: ``{name, token, mode}`` each."""
    return list(load_library().get(kind, {}).get("variants", []))


def variant_tikz(kind: str, variants: dict[str, bool]) -> tuple[str, list[str]]:
    """For a component's active variants, return ``(keyword_suffix, [node_opts])``.

    ``suffix`` mode appends a keyword suffix (``D`` -> ``D*``); ``option`` mode
    adds a node option (``, bodydiode``).
    """
    suffix = ""
    opts: list[str] = []
    for v in variant_specs(kind):
        if variants.get(v["name"]):
            if v["mode"] == "suffix":
                suffix += v["token"]
            else:
                opts.append(v["token"])
    return suffix, opts


def variant_manifest_suffix(kind: str, variants: dict[str, bool]) -> str:
    """The manifest-key suffix for the active variant (e.g. ``"*"``/``"_bodydiode"``).

    Variants are mutually exclusive in practice (at most one active), so the
    first active one wins.  Empty string when none is active.
    """
    for v in variant_specs(kind):
        if variants.get(v["name"]):
            return v["token"] if v["mode"] == "suffix" else "_" + v["token"]
    return ""


def to_component_def(kind: str, entry: dict) -> ComponentDef:
    """Build a registry :class:`ComponentDef` from one library entry."""
    pins = [PinDef(name=p["name"], offset=tuple(p["offset"])) for p in entry["pins"]]
    if len(pins) == 2:
        (x0, y0), (x1, y1) = pins[0].offset, pins[1].offset
        default_span = (x1 - x0, y1 - y0)
    else:
        default_span = (0.0, 0.0)
    return ComponentDef(
        kind=kind,
        display_name=entry["display_name"],
        category=entry["category"],
        bbox=tuple(entry["bbox"]),  # type: ignore[arg-type]
        pins=pins,
        label_slots=list(entry.get("labels", [])),
        tikz_keyword=entry["tikz"],
        default_span=default_span,
        resizable=False,  # every library (SVG-symbol) kind is fixed-size
        # Variants are now generic per-instance state on the base Component, so
        # every library kind uses Component (no DiodeComponent/MosfetComponent).
        component_class=Component,
    )


def library_component_defs() -> dict[str, ComponentDef]:
    """Build the ``ComponentDef`` for every CircuiTikZ-symbol kind in the file."""
    return {kind: to_component_def(kind, entry) for kind, entry in load_library().items()}


def build_codegen_tables() -> dict:
    """Project the ``circuitikz`` codegen tables from the library.

    Alignment is now lead-only: every multi-terminal kind places its node by the
    ``anchor_pin`` (or by centre when null) and bridges every other pin to the
    grid with a lead.  There is no per-component scale, so ``extra_opts`` is empty.
    """
    two: set[str] = set()
    multi: set[str] = set()
    node: set[str] = set()
    diode: set[str] = set()
    anchor_pin: dict[str, tuple[str, str]] = {}
    pin_to_ctikz: dict[str, dict[str, str]] = {}
    leads: dict[str, list[tuple[str, str]]] = {}

    for kind, e in load_library().items():
        if any(v["name"] == "filled" for v in e.get("variants", [])):
            diode.add(kind)
        if e["emission"] == "two_terminal":
            two.add(kind)
        elif e["emission"] == "node":
            node.add(kind)
        else:
            multi.add(kind)
            pin_to_ctikz[kind] = {p["name"]: p["anchor"] for p in e["pins"] if p.get("anchor")}
            if e.get("anchor_pin"):
                ap = e["anchor_pin"]
                ctikz = next((p["anchor"] for p in e["pins"] if p["name"] == ap), None)
                if ctikz:
                    anchor_pin[kind] = (ctikz, ap)
            anchor_to_pin = {p["anchor"]: p["name"] for p in e["pins"] if p.get("anchor")}
            leads[kind] = [
                (ld["anchor"], anchor_to_pin[ld["anchor"]])
                for ld in e.get("leads", []) if ld["anchor"] in anchor_to_pin
            ]

    return {
        "two_terminal_kinds": two,
        "multi_terminal_kinds": multi,
        "node_kinds": node,
        "diode_kinds": diode,
        "anchor_pin": anchor_pin,
        "pin_to_ctikz": pin_to_ctikz,
        "extra_opts": {},  # lead-only alignment — no scale corrections
        "leads": leads,
    }
