"""
Component library — load ``components/definitions.json`` and build the runtime
structures from it (spec: ``spec/component-pipeline.md``).

The file is generated by ``components/generate_components.py`` and holds, for every
CircuiTikZ-symbol kind, its registry + code-generation data (pins, bbox, scale,
metadata) plus a single ``origin_svg`` placement constant.  It replaces the
per-component magic numbers that used to live in ``registry.py``, the
``circuitikz`` codegen tables, and ``svgsym.py``.

The CircuiTikZ-symbol kinds live in the file; the 6 bespoke kinds (the resizable
annotations ``open``/``short`` and the drawing primitives) are not
command-derived and keep their hand-coded ``ComponentDef`` in ``registry.py``.

* :func:`library_component_defs` -> the registry ``ComponentDef``s (used by
  ``registry.py``).
* :func:`build_codegen_tables` -> the ``circuitikz`` classification + alignment
  tables (used by ``app/codegen/circuitikz.py``).
* :func:`origin_svg` -> the constant SVG point that maps to a symbol's origin
  pin (used by ``app/canvas/svgsym.py``).
"""

from __future__ import annotations

import json
import math
from functools import lru_cache
from pathlib import Path

from app.components.model import Component, ComponentDef, PinDef
from app.resources import resource_path

# Kinds NOT in the library (no CircuiTikZ-command symbol) — keep hand-coded defs.
NON_LIBRARY_KINDS: frozenset[str] = frozenset(
    {"open", "short", "bipole", "rect", "circle", "text_node"}
)

#: Body-scale factor applied to every diode-family bipole, in both the emitted
#: LaTeX (``\ctikzset{diodes/scale=…}`` in app/codegen/circuitikz.py) and the
#: rendered canvas SVG assets (app/components/generate.py).  Single-sourced
#: here — the one Qt-free module both consumers already depend on — so the
#: canvas and the compiled output can never drift apart.
DIODE_SYMBOL_SCALE: float = 0.8


def geometry_key(kind: str) -> str:
    """Registry ``kind`` -> ``components/geometry.json`` key.

    The generator sanitises spaces to underscores, so any kind whose CircuiTikZ
    keyword contains a space (``op amp``, ``flipflop D``, …) maps the same way
    everywhere.  Canonical definition — the canvas (``app/canvas/svgsym.py``)
    and the component-editor renderer re-export it.
    """
    return kind.replace(" ", "_")


def library_path() -> Path:
    return Path(resource_path("components", "definitions.json"))


@lru_cache(maxsize=1)
def _data() -> dict:
    path = library_path()
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        # definitions.json is bundled data (heaviside.spec). If it is missing or
        # truncated, the install is corrupt — fail with a clear message instead of
        # an opaque JSONDecodeError/FileNotFoundError deep in REGISTRY building.
        raise RuntimeError(
            f"Heaviside installation is missing or corrupt: could not read the "
            f"component library at {path} ({exc})."
        ) from exc


def load_library() -> dict[str, dict]:
    """The per-kind component records."""
    return _data()["components"]


def origin_svg() -> tuple[float, float]:
    """The constant SVG coordinate that every symbol's origin pin maps to.

    All symbols are rendered in a fixed bounding box with the origin pin at TeX
    (0,0), so this single point is the placement anchor for the canvas transform
    (``svgsym``) — there are no per-component anchors.
    """
    x, y = _data()["origin_svg"]
    return (float(x), float(y))


# ---------------------------------------------------------------------------
# Variants (per-instance boolean attributes, spec §5.4 / §7.4a)
# ---------------------------------------------------------------------------

def variant_specs(kind: str) -> list[dict]:
    """The boolean variants a *kind* declares: ``{name, token, mode}`` each."""
    return list(load_library().get(kind, {}).get("variants", []))


def node_ctikzset(kind: str) -> list[str]:
    """Static ``\\ctikzset`` settings a *kind*'s node must be drawn under — a
    cute/european transformer's ``inductor=…`` shape choice. Codegen wraps such a
    node in its own group so the setting reverts; empty for most kinds."""
    return list(load_library().get(kind, {}).get("ctikzset", []))


def variant_tikz(kind: str, variants: dict[str, bool]) -> tuple[str, list[str]]:
    """For a component's active variants, return ``(keyword_suffix, [node_opts])``.

    ``suffix`` mode appends a keyword suffix (``D`` -> ``D*``); ``option`` mode
    adds a node option (``, bodydiode``).  ``dot`` mode (a transformer polarity
    dot) affects neither — it is drawn separately (see :func:`dot_marks`).
    """
    suffix = ""
    opts: list[str] = []
    for v in variant_specs(kind):
        if variants.get(v["name"]):
            if v["mode"] == "suffix":
                suffix += v["token"]
            elif v["mode"] == "option":
                opts.append(v["token"])
    return suffix, opts


def variant_geometry_suffix(kind: str, variants: dict[str, bool]) -> str:
    """The geometry-key suffix for the active variant (e.g. ``"*"``/``"_bodydiode"``).

    Variants are mutually exclusive in practice (at most one active), so the
    first active one wins.  ``dot`` variants don't change the geometry (the base
    symbol is rendered and the dots are overlaid), so they are skipped.  Empty
    string when none is active.
    """
    for v in variant_specs(kind):
        if v["mode"] != "dot" and variants.get(v["name"]):
            return v["token"] if v["mode"] == "suffix" else "_" + v["token"]
    return ""


def dot_marks(comp: "Component") -> list[dict]:
    """The active **polarity-dot** marks for *comp* (a transformer): one record per
    checked ``dot`` variant — its CircuiTikZ ``anchor`` (for codegen) and ``offset``
    in GU from the component origin (for the canvas). Empty for other kinds / when
    none is set."""
    out: list[dict] = []
    for v in variant_specs(comp.kind):
        if v.get("mode") == "dot" and comp.variants.get(v["name"]):
            out.append({"anchor": v["token"], "offset": tuple(v.get("offset", (0.0, 0.0)))})
    return out


# ---------------------------------------------------------------------------
# Parametric components (variable pin count — e.g. logic gates).  A kind declares
# a ``param`` block; an instance carries an integer value in ``Component.params``.
# ---------------------------------------------------------------------------

def param_specs(kind: str) -> list[dict]:
    """All parametric declarations a *kind* carries, in order. A logic gate has a
    single ``param`` block (one input count); a mux/demux declares a ``params``
    list (data inputs/outputs + select lines). Empty for fixed kinds."""
    e = load_library().get(kind, {})
    if "params" in e:
        return list(e["params"])
    p = e.get("param")
    return [p] if p else []


def param_spec(kind: str) -> dict | None:
    """The *single* gate-style parametric declaration (the ``param`` block), or
    ``None``. Multi-parameter kinds (mux/demux, which use ``params``) return
    ``None`` here — they keep their per-instance geometry in ``n_data`` and are
    handled via :func:`param_specs` / :func:`param_n_data`."""
    return load_library().get(kind, {}).get("param")


def is_parametric(kind: str) -> bool:
    return bool(param_specs(kind))


def _clamp_param(spec: dict, raw: object) -> int:
    return max(int(spec["min"]), min(int(spec["max"]), int(raw)))


def param_value(comp: "Component") -> int | None:
    """The instance's value for its *first* (gate-style) parameter, clamped to
    ``[min, max]``; ``None`` if the kind is not parametric. Used by the
    single-parameter logic-gate paths."""
    specs = param_specs(comp.kind)
    if not specs:
        return None
    spec = specs[0]
    return _clamp_param(spec, comp.params.get(spec["name"], spec["default"]))


def param_values(comp: "Component") -> dict[str, int]:
    """Every parameter value for *comp*, clamped, keyed by name."""
    return {s["name"]: _clamp_param(s, comp.params.get(s["name"], s["default"]))
            for s in param_specs(comp.kind)}


def param_combo_key(comp: "Component") -> str:
    """The ``n_data`` lookup key for this instance: the parameter values in
    declaration order, comma-joined (``"3"`` for a gate, ``"4,2"`` for a mux)."""
    vals = param_values(comp)
    return ",".join(str(vals[s["name"]]) for s in param_specs(comp.kind))


def param_pins(spec: dict, n: int) -> list[dict]:
    """Pins for value *n*: the output plus *n* inputs at the declared pitch,
    symmetric about the output's y (pure — the single source of this layout)."""
    o = spec["output"]
    pins = [{"name": o["name"], "offset": list(o["offset"]), "anchor": o["anchor"]}]
    inp = spec["input"]
    for i in range(n):
        y = round((i - (n - 1) / 2) * inp["pitch"], 4)
        pins.append({"name": inp["name"].format(i=i + 1),
                     "offset": [inp["x"], y],
                     "anchor": inp["anchor"].format(i=i + 1)})
    return pins


def resolved_pins(comp: "Component") -> list[PinDef]:
    """The pins for this instance — for a parametric kind computed from the
    parameter(s), else the kind's static registry pins.

    Multi-parameter kinds (mux/demux) carry their measured pins per value-combo in
    ``n_data[...]["pins"]``; single-parameter logic gates compute theirs from the
    input template (:func:`param_pins`)."""
    specs = param_specs(comp.kind)
    if not specs:
        from app.components.registry import REGISTRY
        defn = REGISTRY.get(comp.kind)
        return list(defn.pins) if defn else []
    nd = param_n_data(comp)
    if nd and "pins" in nd:                      # measured-pins (mux/demux)
        return [PinDef(name=p["name"], offset=tuple(p["offset"])) for p in nd["pins"]]
    return [PinDef(name=p["name"], offset=tuple(p["offset"]))   # template (gates)
            for p in param_pins(specs[0], param_value(comp))]


def param_geometry_suffix(comp: "Component") -> str:
    """Geometry-key suffix for a parametric instance: one ``":v"`` per parameter in
    declaration order (``":3"`` for a gate, ``":4:2"`` for a mux); ``""`` for fixed
    kinds."""
    vals = param_values(comp)
    return "".join(f":{vals[s['name']]}" for s in param_specs(comp.kind))


def param_n_data(comp: "Component") -> dict | None:
    """The per-combo record for this instance. Gates keep it under
    ``param.n_data`` keyed by the single value; multi-parameter kinds keep it at
    the entry's ``n_data`` keyed by the comma-joined value combo."""
    if not is_parametric(comp.kind):
        return None
    e = load_library().get(comp.kind, {})
    nd = e.get("n_data") or e.get("param", {}).get("n_data", {})
    return nd.get(param_combo_key(comp))


# ── Logic-gate scaling (per-instance Component.scale) ───────────────────────
# Logic gates can be uniformly scaled.  Their pins sit at the *true* scaled body
# anchor (``base_offset * scale``), generally **off the 0.25-GU grid** — a wire
# connects there directly because endpoints snap onto component pins (the magnet,
# wiregeometry.py), so no grid-snapping lead stub is needed and the connection is
# an ordinary, styleable wire (model.py Component.scale, spec §5.4).

_QUARTER_GU = 0.25
DEFAULT_GATE_SCALE = 1.0      # placed full size, matching the digital blocks
MIN_GATE_SCALE = 0.25        # floor: smaller gates render too small to read/grab


def is_logic_gate(kind: str) -> bool:
    """True for logic-gate kinds (CircuiTikZ keyword ending in `` port``)."""
    e = load_library().get(kind)
    return bool(e) and str(e.get("tikz", "")).endswith(" port")


# Block kinds (flip-flops, mux/demux, ALU, adder) that, like logic gates, carry a
# per-instance :attr:`Component.scale`.  They additionally bake a best-effort
# grid-alignment scale into their geometry (see :func:`block_scale`) so their pins
# land on the grid at scale 1.0 where a uniform rescale can manage it; the rest
# stay off-grid and connect via the magnet, exactly like a gate.  (Transformers
# keep their baked alignment scale but are *not* user-scalable — they behave like
# the other passive symbols.)
_SCALABLE_BLOCK_TIKZ = ("flipflop", "muxdemux", "ALU", "one bit adder")


def is_scalable(kind: str) -> bool:
    """True for every kind whose :attr:`Component.scale` is meaningful — logic
    gates and the digital blocks."""
    if is_logic_gate(kind):
        return True
    tk = str(load_library().get(kind, {}).get("tikz", ""))
    return any(tk == t or tk.startswith(t + " ") for t in _SCALABLE_BLOCK_TIKZ)


def block_scale(comp: "Component") -> list[float]:
    """The baked **grid-alignment** scale ``[sx, sy]`` of *comp*'s symbol (the
    uniform rescale applied at generation so its pins land on the grid). Lives in
    the per-combo ``n_data`` for a parametric kind, else on the entry; ``[1, 1]``
    when none."""
    nd = param_n_data(comp)
    if nd and nd.get("scale"):
        return [float(s) for s in nd["scale"]]
    e = load_library().get(comp.kind, {})
    return [float(s) for s in (e.get("scale") or (1.0, 1.0))]


def default_scale(kind: str) -> float:
    """The :attr:`Component.scale` a freshly-placed *kind* gets: logic gates start
    at :data:`DEFAULT_GATE_SCALE` (compact), everything else unscaled (1.0)."""
    return DEFAULT_GATE_SCALE if is_logic_gate(kind) else 1.0


def snap_quarter(v: float) -> float:
    """Round *v* to the nearest 0.25 GU, ties **away from zero** so a symmetric
    pair of input pins stays distinct and symmetric after snapping."""
    if v == 0.0:
        return 0.0
    sign = 1.0 if v > 0 else -1.0
    return sign * math.floor(abs(v) / _QUARTER_GU + 0.5) * _QUARTER_GU


def _pin_anchor_map(comp: "Component") -> dict[str, str]:
    """Map each pin name to its CircuiTikZ anchor name for *comp*'s kind."""
    nd = param_n_data(comp)
    if nd and "pins" in nd:                  # measured-pins (mux/demux)
        return {p["name"]: p.get("anchor", p["name"]) for p in nd["pins"]}
    spec = param_spec(comp.kind)
    if spec is not None:                     # template (logic gates)
        return {p["name"]: p["anchor"] for p in param_pins(spec, param_value(comp))}
    e = load_library().get(comp.kind, {})
    return {p["name"]: p.get("anchor", p["name"]) for p in e.get("pins", [])}


def gate_layout(comp: "Component") -> list[dict] | None:
    """Per-pin scaled layout for a **scaled** gate/digital-block instance, else
    ``None``.

    Returns ``None`` for non-scalable kinds and at scale 1.0 (the base pins —
    already grid-aligned where possible — are used as-is). Otherwise returns one
    entry per pin (in :func:`resolved_pins` order):

    * ``name`` / ``anchor`` — pin name and its CircuiTikZ anchor.
    * ``anchor_offset`` / ``pin_offset`` — the base pin ``× scale``; these are
      **equal** (the pin sits at the true scaled anchor, generally off the 0.25-GU
      grid, reached directly by a wire endpoint via the pin magnet — no lead).

    The body is scaled about the placement origin (a gate's ``out`` pin, a block's
    centre)."""
    if not is_scalable(comp.kind):
        return None
    s = float(getattr(comp, "scale", 1.0))
    if abs(s - 1.0) < 1e-9:
        return None
    anchors = _pin_anchor_map(comp)
    out: list[dict] = []
    for p in resolved_pins(comp):
        ax, ay = p.offset[0] * s, p.offset[1] * s
        out.append({
            "name": p.name,
            "anchor": anchors.get(p.name, p.name),
            "anchor_offset": (ax, ay),
            "pin_offset": (ax, ay),     # pin = true scaled anchor (magnet connects)
        })
    return out


def gate_scale_options(kind: str) -> list[float]:
    """The `scale` choices offered for a scalable *kind* in the inspector: 25 %–
    200 % (floored at :data:`MIN_GATE_SCALE`). Pins sit at the true scaled anchor
    and are reached by the magnet, so any scale is grid-connectable. Empty for
    non-scalable kinds."""
    if not is_scalable(kind):
        return []
    return [s for s in (0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0)
            if s >= MIN_GATE_SCALE - 1e-9]


def to_component_def(kind: str, entry: dict) -> ComponentDef:
    """Build a registry :class:`ComponentDef` from one library entry."""
    pins = [PinDef(name=p["name"], offset=tuple(p["offset"])) for p in entry["pins"]]
    # A path (``to[…]``) bipole spans between its two axial terminals (pins[0] →
    # pins[1]); any further pins are off-axis taps (e.g. the thyristor/triac gate)
    # and don't affect the span. Node-placed kinds don't use default_span.
    if entry.get("emission") == "path" and len(pins) >= 2:
        (x0, y0), (x1, y1) = pins[0].offset, pins[1].offset
        default_span = (x1 - x0, y1 - y0)
    else:
        default_span = (0.0, 0.0)
    return ComponentDef(
        kind=kind,
        display_name=entry["display_name"],
        category=entry["category"],
        bbox=tuple(entry["bbox"]),  # type: ignore[arg-type]
        pins=pins,
        label_slots=list(entry.get("labels", [])),
        tikz_keyword=entry["tikz"],
        default_span=default_span,
        resizable=False,  # every library (SVG-symbol) kind is fixed-size
        # Variants are now generic per-instance state on the base Component, so
        # every library kind uses Component (no DiodeComponent/MosfetComponent).
        component_class=Component,
        # Measured node-text anchor offset (components/add_text_anchors.py); (0,0)
        # when absent.
        text_anchor=tuple(entry.get("text_anchor", (0.0, 0.0))),  # type: ignore[arg-type]
    )


def library_component_defs() -> dict[str, ComponentDef]:
    """Build the ``ComponentDef`` for every CircuiTikZ-symbol kind in the file."""
    return {kind: to_component_def(kind, entry) for kind, entry in load_library().items()}


def is_multi_terminal_entry(entry: dict) -> bool:
    """True for a *node*-emission element with CircuiTikZ-anchored pins.

    Emission classifies a component by its LaTeX syntax: ``path`` (``to[…]``) or
    ``node`` (``node[…]``).  Within ``node`` there are two flavours, distinguished
    by the *data* rather than a third emission type: a single-point node (grounds,
    power rails — no anchored pins) and a multi-terminal node (op amps,
    transistors, logic gates), centre-placed and aligned by a per-axis scale, with
    each pin mapped to a CircuiTikZ anchor.  A node element is multi-terminal when
    any pin maps to a CircuiTikZ anchor.
    """
    if entry.get("emission") != "node":
        return False
    return any((p.get("anchor") or "").strip() for p in entry.get("pins", []))


def _scale_opts(scale) -> str:
    """Format a ``[sx, sy]`` scale as a ``xscale=…, yscale=…`` node-option string."""
    if not scale:
        return ""
    parts = []
    if abs(scale[0] - 1.0) > 1e-9:
        parts.append(f"xscale={scale[0]:g}")
    if abs(scale[1] - 1.0) > 1e-9:
        parts.append(f"yscale={scale[1]:g}")
    return ", ".join(parts)


def build_codegen_tables() -> dict:
    """Project the ``circuitikz`` codegen tables from the library.

    Every multi-terminal node is centre-placed and aligned by a per-component
    per-axis scale (``extra_opts``, the ``xscale=…, yscale=…`` that lands its
    anchors on the grid); pins connect via their named anchors (``pin_to_ctikz``).
    The scale is computed (measured), not hand-typed.
    """
    two: set[str] = set()
    multi: set[str] = set()
    node: set[str] = set()
    diode: set[str] = set()
    pin_to_ctikz: dict[str, dict[str, str]] = {}
    extra_opts: dict[str, str] = {}

    for kind, e in load_library().items():
        if any(v["name"] == "filled" for v in e.get("variants", [])):
            diode.add(kind)
        if e["emission"] == "path":
            two.add(kind)
        elif not is_multi_terminal_entry(e):
            node.add(kind)
        else:
            multi.add(kind)
            pin_to_ctikz[kind] = {p["name"]: p["anchor"] for p in e["pins"] if p.get("anchor")}
            if (opts := _scale_opts(e.get("scale"))):
                extra_opts[kind] = opts

    return {
        "two_terminal_kinds": two,
        "multi_terminal_kinds": multi,
        "node_kinds": node,
        "diode_kinds": diode,
        "pin_to_ctikz": pin_to_ctikz,
        "extra_opts": extra_opts,
    }
