"""
Component generation pipeline tests (spec/component-pipeline.md).

The Qt-free core in ``app/components/generate.py`` (data entries, alignment,
validation, the store) is tested directly; the render paths are gated on
latex/dvisvgm.
"""

from __future__ import annotations

import shutil

import pytest

from app.components import generate as renderer
from app.components import render as comp_render

_HAVE_TOOLCHAIN = bool(shutil.which("latex") and shutil.which("dvisvgm"))


def _opamp_entry() -> dict:
    return {
        "display_name": "Op-Amp", "category": "Amplifiers",
        "emission": "node", "tikz": "op amp", "labels": ["l"],
        "bbox": [-1.5, -1.0, 1.5, 1.0],
        "pins": [
            {"name": "+", "offset": [-1.5, 0.5], "anchor": "+"},
            {"name": "-", "offset": [-1.5, -0.5], "anchor": "-"},
            {"name": "out", "offset": [1.5, 0.0], "anchor": "out"},
        ],
    }


def _resistor_entry() -> dict:
    return {
        "display_name": "Resistor", "category": "Resistors",
        "emission": "path", "tikz": "R", "labels": ["l"],
        "bbox": [0.0, -0.25, 2.0, 0.25],
        "pins": [
            {"name": "in", "offset": [0.0, 0.0], "anchor": None},
            {"name": "out", "offset": [2.0, 0.0], "anchor": None},
        ],
    }


# ---------------------------------------------------------------------------
# renderer.data_entry — record shape (scale-only, no anchor_pin / leads)
# ---------------------------------------------------------------------------

def test_data_entry_has_no_anchor_pin_or_leads():
    """Every node is centre-placed and aligned by scale alone (§4) — the record
    carries no `anchor_pin` and no `leads`, and the pins pass through verbatim."""
    e = renderer.data_entry("op amp", {**_opamp_entry(), "scale": [1.0504, 1.0]})
    assert "anchor_pin" not in e
    assert "leads" not in e
    assert e["scale"] == [1.0504, 1.0]
    assert [(p["name"], p["anchor"]) for p in e["pins"]] == [
        ("+", "+"), ("-", "-"), ("out", "out")]


def test_data_entry_omits_unit_scale():
    """A `[1, 1]` scale is dropped (omitted when no stretch); a node with no
    authored scale gets no scale field."""
    e = renderer.data_entry("op amp", _opamp_entry())   # no scale on the fixture
    assert "scale" not in e


def test_compute_bbox_from_ink_extent_union_pins():
    # SVG coords for a symbol spanning x:[0,1.02] GU, y:[-0.21,0.21] GU about the
    # origin, with pins at (0,0) and (1,0).  The bbox = ink ∪ pins, rounded
    # outward to 0.05.
    ox = oy = 15.0312
    K = 28.34765
    geom = {
        "paths": [{"d": f"M{ox} {oy - 0.21 * K} L{ox + 1.02 * K} {oy + 0.21 * K}"}],
        "glyphs": [],
    }
    pins = [{"name": "in", "offset": [0, 0]}, {"name": "out", "offset": [1, 0]}]
    assert renderer.compute_bbox(geom, (ox, oy), pins) == [0.0, -0.25, 1.05, 0.25]


def test_compute_bbox_handles_hv_and_curves():
    # H/V (axis moves) and C (control points) must not desync coordinate pairing.
    ox = oy = 15.0312
    K = 28.34765
    geom = {
        "paths": [{
            "d": (f"M{ox} {oy}H{ox + 0.5 * K}V{oy - 0.3 * K}"
                  f"C{ox + 0.5 * K} {oy - 0.3 * K} {ox + 0.5 * K} {oy} {ox + K} {oy}"),
        }],
        "glyphs": [],
    }
    pins = [{"name": "p", "offset": [0, 0]}]
    # x spans 0..1.0, y spans -0.3..0 (Qt y-down) -> rounds to clean 0.05 grid.
    assert renderer.compute_bbox(geom, (ox, oy), pins) == [0.0, -0.3, 1.0, 0.0]


def test_param_pins_computes_symmetric_inputs():
    """A parametric component's pins: output + N inputs at the declared pitch,
    symmetric about the output's y, named/anchored by the templates."""
    entry = {"param": {
        "input": {"name": "in{i}", "anchor": "in {i}", "x": -1.5, "pitch": 0.5},
        "output": {"name": "out", "anchor": "out", "offset": [0, 0]}}}
    got = [(p["name"], tuple(p["offset"]), p["anchor"]) for p in renderer.param_pins(entry, 3)]
    assert got == [
        ("out", (0, 0), "out"),
        ("in1", (-1.5, -0.5), "in 1"),
        ("in2", (-1.5, 0.0), "in 2"),
        ("in3", (-1.5, 0.5), "in 3"),
    ]
    assert len(renderer.param_pins(entry, 7)) == 8   # output + 7 inputs


# NOTE: removed test_and_gate_is_parametric_in_the_data — it read the curated
# definitions.json (renderer.DEFINITIONS_PATH), which was deleted along with the
# curated library. The manual library is now generated by
# components/generate_library.py, which owns its own data files.


def test_variant_key():
    assert renderer.variant_key("D", {"name": "filled", "token": "*", "mode": "suffix"}) == "D*"
    assert renderer.variant_key("nigfete", {"name": "body_diode", "token": "bodydiode",
                                         "mode": "option"}) == "nigfete_bodydiode"


# ---------------------------------------------------------------------------
# validate_entry — the batch generator's pre-flight
# ---------------------------------------------------------------------------

def test_validate_clean():
    assert renderer.validate_entry("R", _resistor_entry()) == []
    assert renderer.validate_entry("op amp", _opamp_entry()) == []


def test_validate_off_grid_pin():
    e = _resistor_entry()
    e["pins"][1]["offset"] = [2.1, 0.0]
    assert any("0.25 GU grid" in m for m in renderer.validate_entry("R", e))


def test_validate_multi_terminal_needs_anchor():
    e = _opamp_entry()
    e["pins"][0]["anchor"] = None
    assert any("CircuiTikZ anchor" in m for m in renderer.validate_entry("op amp", e))


def test_validate_requires_kind_and_keyword():
    e = _resistor_entry()
    e["tikz"] = ""
    msgs = renderer.validate_entry("", e)
    assert any("Kind is required" in m for m in msgs)
    assert any("keyword is required" in m for m in msgs)


def test_validate_allows_measured_off_grid_styles():
    """Measured pins are legitimately off-grid: a path bipole's off-axis tap
    (thyristor gate), a centre-placed entry with a uniform grid scale, and a
    muxdemux entry (no authored pins at all) must all validate clean."""
    tap = _resistor_entry()
    tap["pins"].append({"name": "gate", "offset": [1.7, -0.77], "anchor": None})
    assert renderer.validate_entry("thyristor", tap) == []

    scaled = {**_opamp_entry(), "scale": [0.8929, 0.8929]}
    scaled["pins"] = [{**p, "offset": [-1.12, -0.56]} for p in scaled["pins"]]
    assert renderer.validate_entry("flipflop D", scaled) == []

    muxd = {"display_name": "Multiplexer", "category": "Logic",
            "emission": "node", "tikz": "muxdemux",
            "muxdemux": {"role": "mux", "data_param": "inputs",
                         "select_param": "selects"}}
    assert renderer.validate_entry("mux", muxd) == []


# NOTE: removed test_validate_every_shipped_entry — it called the deleted
# renderer.load_authored(), which read the curated definitions.json. The
# manual library has no committed authored-store to pre-flight here.


def test_data_entry_derives_component_def():
    from app.components import library
    cdef = library.to_component_def("R", renderer.data_entry("R", _resistor_entry()))
    assert cdef.kind == "R"
    assert cdef.default_span == (2.0, 0.0)
    assert [p.name for p in cdef.pins] == ["in", "out"]


# ---------------------------------------------------------------------------
# Render paths (gated on toolchain)
# ---------------------------------------------------------------------------

# NOTE: removed the curated-store render tests — they all read the deleted
# curated definitions.json / geometry.json (renderer.DEFINITIONS_PATH /
# GEOMETRY_PATH) or drove the removed curated batch-store I/O:
#   - test_render_store_reproduces_committed_files (renderer.render_store +
#     committed curated files)
#   - test_best_alignment_uniform_scale_and_pins / _scale_within_bounds (both
#     read curated entries by curated kind name from definitions.json)
#   - test_save_component_round_trips (renderer.save_component)
# best_alignment is still covered as a pure function by the monkeypatched
# test_best_alignment_* tests below (measurement stubbed, inline entries).


# ---------------------------------------------------------------------------
# best_alignment / render_muxdemux — pure derivation (measurement stubbed)
# ---------------------------------------------------------------------------

def test_best_alignment_grids_pins_and_picks_scale_nearest_one(monkeypatch):
    """The uniform algorithm scales each axis to land the measured anchors on the
    grid, choosing the grid-landing scale nearest 1.0, and bakes the scaled
    offsets into the pins (no anchor_pin / leads). Pure — measurement stubbed."""
    entry = {
        "display_name": "D Flip-flop", "category": "Logic", "emission": "node",
        "tikz": "flipflop D", "labels": [],
        "pins": [{"name": "D", "offset": [0, 0], "anchor": "pin 1"},
                 {"name": "Q", "offset": [0, 0], "anchor": "pin 3"}],
    }
    measured = {"pin 1": (-1.12, -0.56), "pin 3": (1.12, -0.56)}
    monkeypatch.setattr(renderer.render, "measure_anchors",
                        lambda kw, anchors, ctikzset=None: measured)

    scale, pins = renderer.best_alignment(entry)
    # 1.12 * 0.8929 == 1.0 and 0.56 * 0.8929 == 0.5: pins snap to the grid.
    assert scale == [0.8929, 0.8929]
    assert [p["offset"] for p in pins] == [[-1.0, -0.5], [1.0, -0.5]]


def test_best_alignment_keeps_offgrid_pin_when_no_in_bounds_scale(monkeypatch):
    """A coordinate no in-bounds scale can grid stays at its true scaled value
    (reached by the magnet) rather than forcing a distorting scale."""
    entry = {
        "display_name": "X", "category": "C", "emission": "node", "tikz": "x",
        "pins": [{"name": "a", "offset": [0, 0], "anchor": "a"},
                 {"name": "b", "offset": [0, 0], "anchor": "b"}],
    }
    # 'a' grids at sx=1.0; 'b' would need ~1.6 (out of [0.7,1.3]) → stays off-grid.
    measured = {"a": (1.0, 0.0), "b": (0.157, 0.0)}
    monkeypatch.setattr(renderer.render, "measure_anchors",
                        lambda kw, anchors, ctikzset=None: measured)

    scale, pins = renderer.best_alignment(entry)
    assert scale is None                       # sx = sy = 1.0
    off = {p["name"]: p["offset"] for p in pins}
    assert off["a"] == [1.0, 0.0]
    assert off["b"] == [0.157, 0.0]            # off-grid, kept verbatim


# NOTE: removed test_render_store_routes_muxdemux — it drove the removed
# renderer.render_store() batch pipeline. render_muxdemux itself (the surviving
# shared helper that generate_library.py calls) is still covered directly by
# test_render_muxdemux_persists_authoring_rec below.


def test_render_muxdemux_persists_authoring_rec(monkeypatch):
    """The stored mux/demux record carries its 'muxdemux' authoring rec, so the
    generator can re-render the combos from its source definition alone."""
    monkeypatch.setattr(renderer, "_muxdemux_combo", lambda role, d, s: (
        f"muxdemux def={{NL=1, NR={d}, NB={s}}}",
        {"lpin 1": (-1.0, 0.5), "rpin 1": (1.0, 0.5), "bpin 1": (0.0, -1.0)},
        [("in", "lpin 1"), ("out0", "rpin 1"), ("sel0", "bpin 1")]))
    monkeypatch.setattr(renderer, "geometry",
                        lambda e, option="": {"viewBox": [0, 0, 1, 1],
                                              "paths": [], "glyphs": []})
    monkeypatch.setattr(renderer, "compute_bbox", lambda g, o, p: [-1, -1, 1, 1])

    rec = {"role": "demux", "data_param": "outputs", "select_param": "selects"}
    entry = {
        "display_name": "Demultiplexer", "category": "Logic",
        "emission": "node", "tikz": "muxdemux", "labels": [],
        "params": [{"name": "outputs", "min": 2, "max": 2, "default": 2},
                   {"name": "selects", "min": 1, "max": 1, "default": 1}],
        "muxdemux": rec,
    }
    geoms, de = renderer.render_muxdemux("demux", entry, (15.0, 15.0))
    assert de["muxdemux"] == rec
    assert set(de["n_data"]) == {"2,1"}
    assert set(geoms) == {"demux:2:1", "demux"}


# ---------------------------------------------------------------------------
# CircuiTikZ generation-version stamp
# ---------------------------------------------------------------------------

def test_render_doc_probes_circuitikz_version():
    """Every measurement compile typesets the installed CircuiTikZ version
    (guarded by \\ifdefined so pre-macro versions still compile)."""
    assert r"\typeout{HVCTIKZVERSION \pgfcircversion}" in comp_render._DOC
    assert r"\ifdefined\pgfcircversion" in comp_render._DOC


def test_circuitikz_version_parses_probe_and_banner():
    # Primary: the HVCTIKZVERSION line from _DOC's probe.
    log = "blah\nHVCTIKZVERSION 1.6.4\nHVANCHOR out = 28.4pt , 0.0pt\n"
    assert comp_render.circuitikz_version(log) == "1.6.4"
    # Fallback: the package's log banner (pre-\pgfcircversion releases).
    banner = "Package: circuitikz 2021/01/01 The CircuiTikZ package version 1.2.7\n"
    assert comp_render.circuitikz_version(banner) == "1.2.7"
    # Neither present -> unknown.
    assert comp_render.circuitikz_version("no version info here") is None


# NOTE: removed test_write_store_stamps_circuitikz_version — it drove the
# removed renderer.write_store() curated batch-store writer (and its
# DEFINITIONS_PATH / GEOMETRY_PATH targets). The version-string parsing it
# relied on is still covered by test_circuitikz_version_parses_probe_and_banner.


