"""
SVG-symbol translation layer for canvas painting.

Component symbols are *not* hand-coded.  They are derived from the CircuiTikZ
SVG exports compiled into the **self-contained** manifest
``tools/circuitikz_svgs/manifest.json`` (generated by
``tools/export_circuitikz_svgs.py``).  This module reads **only** the manifest —
it never touches the ``.svg`` files at run time.

Each manifest entry carries two geometry lists (both in SVG point coordinates):

  * ``paths``  — the stroked/filled body geometry; and
  * ``glyphs`` — text marks (the ``+``/``−`` of sources) pre-resolved from the
    SVG's ``<use>``/``<defs>`` indirection into a path ``d`` plus a baked affine
    ``matrix``.

This module:

  * loads and caches the manifest,
  * parses each path ``d`` string into a :class:`QPainterPath`
    (supporting the ``M / L / H / V / C / S / Q / Z`` commands emitted by
    ``dvisvgm``),
  * applies a per-component affine transform that maps the SVG point
    coordinate space into the component's *local* pixel space (origin at the
    component origin pin, scaled by ``GRID_PX``) so the painted symbol lines up
    with the :class:`~app.components.model.PinDef` offsets in the registry.

The mapping from SVG path command to ``QPainterPath`` call follows §5.2 of the
spec:

    M x y              -> path.moveTo(x, y)
    L x y              -> path.lineTo(x, y)
    H x                -> path.lineTo(x, currentY)
    V y                -> path.lineTo(currentX, y)
    C x1 y1 x2 y2 x y  -> path.cubicTo(x1, y1, x2, y2, x, y)
    Z                  -> path.closeSubpath()

``dvisvgm`` may additionally emit ``S`` (smooth cubic) — used by the inductor
humps — and (rarely) ``Q`` (quadratic); both are handled here.

The SVG y-axis matches Qt's (y increases downward), so no axis flip is needed.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache

from PySide6.QtGui import QPainterPath, QTransform

from app.canvas.style import GRID_PX, MANIFEST_PATH, SVG_PT_PER_GU

# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def _manifest() -> dict:
    """Load and cache the SVG manifest as a dict keyed by node name."""
    with open(MANIFEST_PATH, encoding="utf-8") as fh:
        return json.load(fh)


# Registry ``kind`` -> manifest key.  Most kinds match the CircuiTikZ keyword
# verbatim; only "op amp" differs (the export script sanitises the space).
_KIND_TO_MANIFEST: dict[str, str] = {
    "op amp": "op_amp",
}


def manifest_key(kind: str) -> str:
    return _KIND_TO_MANIFEST.get(kind, kind)


# ---------------------------------------------------------------------------
# Path-string parsing
# ---------------------------------------------------------------------------

_CMD_RE = re.compile(r"[MLHVCSQTZ]|[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?")


def parse_path(d: str) -> QPainterPath:
    """
    Translate an SVG path ``d`` string into a :class:`QPainterPath`.

    Only the absolute-coordinate commands produced by ``dvisvgm`` are handled
    (``M L H V C S Q Z``).  Coordinates are left in SVG point units; callers
    apply the local-space transform separately.
    """
    path = QPainterPath()
    tokens = _CMD_RE.findall(d)
    j = 0
    cmd: str | None = None
    cx = cy = 0.0
    # Tracking last cubic control point for the smooth-curve (``S``) reflection.
    last_c2x = last_c2y = None  # type: ignore[assignment]

    def _f(idx: int) -> float:
        return float(tokens[idx])

    while j < len(tokens):
        tok = tokens[j]
        if tok in "MLHVCSQTZ":
            cmd = tok
            j += 1
            if cmd == "Z":
                path.closeSubpath()
                cmd = None
                last_c2x = last_c2y = None
                continue
        if cmd is None:
            j += 1
            continue

        if cmd == "M":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.moveTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "L":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "H":
            cx = _f(j)
            j += 1
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "V":
            cy = _f(j)
            j += 1
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "C":
            x1, y1, x2, y2, x, y = (_f(j + k) for k in range(6))
            j += 6
            path.cubicTo(x1, y1, x2, y2, x, y)
            cx, cy = x, y
            last_c2x, last_c2y = x2, y2
        elif cmd == "S":
            # Smooth cubic: first control point is the reflection of the
            # previous curve's second control point about the current point.
            x2, y2, x, y = (_f(j + k) for k in range(4))
            j += 4
            if last_c2x is None:
                x1, y1 = cx, cy
            else:
                x1, y1 = 2 * cx - last_c2x, 2 * cy - last_c2y
            path.cubicTo(x1, y1, x2, y2, x, y)
            cx, cy = x, y
            last_c2x, last_c2y = x2, y2
        elif cmd == "Q":
            x1, y1, x, y = (_f(j + k) for k in range(4))
            j += 4
            path.quadTo(x1, y1, x, y)
            cx, cy = x, y
            last_c2x = last_c2y = None
        elif cmd == "T":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        else:  # pragma: no cover - defensive
            j += 1

    return path


# ---------------------------------------------------------------------------
# Per-component placement transform
# ---------------------------------------------------------------------------
#
# Every export shares one uniform scale: the bipole terminal span of
# 56.6953 pt corresponds to exactly 2 GU, i.e. SVG_PT_PER_GU = 28.34765.
# A component's symbol is placed by:
#
#   1. translating the SVG anchor point to the local origin,
#   2. optionally rotating 90 deg (the source bodies are drawn horizontally in
#      the SVG but stand vertically in the registry),
#   3. scaling SVG points to local pixels  (GRID_PX / SVG_PT_PER_GU).
#
# ``Placement`` records the SVG anchor (which SVG point becomes local (0,0))
# and the rotation in degrees applied about that anchor.

_PX_PER_PT = GRID_PX / SVG_PT_PER_GU

# Bipole terminal x-coordinates in the SVG (constant across all bipoles).
_BIPOLE_IN_X = -69.808597
_BIPOLE_OUT_X = -13.1133


@dataclass(frozen=True)
class Placement:
    anchor: tuple[float, float]  # SVG point mapped to local (0, 0)
    rotate_deg: float = 0.0      # rotation about the anchor, applied after translate
    xscale: float = 1.0          # horizontal scale applied to symbol paths only
    yscale: float = 1.0          # vertical scale applied to symbol paths only
                                 # xscale/yscale correct CTikZ internal geometry
                                 # mismatches; they do not move pin positions.
                                 # See §5.5 of PROJECT_SPEC.md for the procedure.


# Horizontal two-terminal devices: lead axis y read from the manifest at load
# time (it differs per component).  ``in`` pin = SVG (_BIPOLE_IN_X, lead_y).
_HORIZONTAL_BIPOLES = {"R", "C", "L", "D", "zD", "sD", "tD", "zzD", "leD"}

# Vertical sources: the SVG draws them horizontally; rotate +90 deg so the
# SVG +x axis becomes local +y (registry pins at (0,0) and (0,2)).
_VERTICAL_SOURCES = {"V", "I", "vsourcesin", "isourcesin", "cV", "cI"}

# Multi-terminal anchors are taken directly from the SVG terminal points.
_MULTI_ANCHORS: dict[str, Placement] = {
    # These SVGs are exported with explicit grid-aligned terminal leads (see
    # tools/export_circuitikz_svgs.py TRIPOLES leads), so every terminal sits
    # on the registry pin grid with no run-time bridging needed.  The anchor is
    # simply the SVG point that maps to the component's local origin.
    #
    # op amp: origin = node center.  Terminals (grid units, Qt y-down) are then
    # + (-1.5,+0.5), - (-1.5,-0.5), out (1.5,0).  Power supply pins omitted.
    "op amp": Placement(anchor=(-19.3183, -33.8613)),
    # Ground / reference node symbols: origin = connection pin at the top.
    # Anchor = SVG coordinate of the first point of the vertical lead (the
    # connection point at circuit (0,0)).  Symbol extends downward in local space.
    "ground":  Placement(anchor=(-63.65625, -69.808597)),
    "rground": Placement(anchor=(-63.65625, -69.808597)),
    "sground": Placement(anchor=(-63.65625, -69.808597)),
    "nground": Placement(anchor=(-60.679687, -69.808597)),
    "pground": Placement(anchor=(-60.679687, -69.609374)),
    "cground": Placement(anchor=(-59.687499, -69.808597)),
    "eground": Placement(anchor=(-58.894533, -69.808597)),
    # Power rails: vcc/vdd point up (pin at bottom of stem), vee/vss point down (pin at top).
    # Anchor = SVG coordinate of the stem endpoint that is the connection pin.
    "vcc": Placement(anchor=(-65.640623, -54.132812)),
    "vdd": Placement(anchor=(-65.640623, -54.132812)),
    "vee": Placement(anchor=(-65.640623, -69.808597)),
    "vss": Placement(anchor=(-65.640623, -69.808597)),

    # npn / pnp: origin = base terminal (endpoint of the base lead stub).
    # SVG base terminal measured from re-exported manifest: (-61.8398, -33.492188).
    # Collector/emitter sit at (1.013, ±1.0) GU from base; 0.013 GU x-error is
    # sub-pixel (~0.8 px) so no xscale correction is applied.
    "npn": Placement(anchor=(-61.8398, -33.492188)),
    "pnp": Placement(anchor=(-61.8398, -33.492188)),

    # nigfete / nigfetd: origin = gate terminal (end of the gate lead).
    # Terminals: drain (1.0,-1), source (1.0,+0.5), gate (0,0).
    # xscale=1.0167 stretches the body so drain/source x aligns with the
    # 1.0 GU registry pin (CTikZ internal x = 0.9836 GU; 0.9836×1.0167≈1.0).
    "nigfete": Placement(anchor=(-61.7422, -32.14453), xscale=1.0167),
    "nigfetd": Placement(anchor=(-61.7422, -32.14453), xscale=1.0167),
    # bodydiode variants share the same gate anchor; body diode extends rightward.
    "nigfete_bodydiode": Placement(anchor=(-61.7422, -32.14453), xscale=1.0167),
    "nigfetd_bodydiode": Placement(anchor=(-61.7422, -32.14453), xscale=1.0167),

    # pigfete / pigfetd: same x geometry as nigfete but gate is higher (y-mirrored).
    # Terminals: source (1.0,-0.5), drain (1.0,+1.0), gate (0,0).
    "pigfete": Placement(anchor=(-61.7422, -47.48047), xscale=1.0167),
    "pigfetd": Placement(anchor=(-61.7422, -47.48047), xscale=1.0167),
    "pigfete_bodydiode": Placement(anchor=(-61.7422, -47.48047), xscale=1.0167),
    "pigfetd_bodydiode": Placement(anchor=(-61.7422, -47.48047), xscale=1.0167),
}


def _lead_y(key: str) -> float:
    """Read the y of a horizontal bipole's lead axis from its first lead path."""
    for p in _manifest()[key]["paths"]:
        d = p["d"]
        mobj = re.match(r"^M(-?[\d.]+)(-?[\d.]+)", d)
        if mobj and abs(float(mobj.group(1)) - _BIPOLE_IN_X) < 0.5:
            return float(mobj.group(2))
    raise ValueError(f"no lead path found for {key!r}")


def _placement(kind: str) -> Placement:
    # Filled variants (e.g. "zD*") share geometry with their base kind ("zD").
    base = kind[:-1] if kind.endswith("*") else kind
    key = manifest_key(kind)
    if base in _HORIZONTAL_BIPOLES:
        return Placement(anchor=(_BIPOLE_IN_X, _lead_y(key)))
    if base in _VERTICAL_SOURCES:
        return Placement(anchor=(_BIPOLE_IN_X, _lead_y(key)), rotate_deg=90.0)
    if base in _MULTI_ANCHORS:
        return _MULTI_ANCHORS[base]
    raise KeyError(f"no placement defined for kind {kind!r}")


@lru_cache(maxsize=None)
def _local_transform(kind: str) -> QTransform:
    """
    Affine transform mapping SVG point coordinates to local pixel coordinates
    (origin at the component origin pin, scaled by GRID_PX).
    """
    pl = _placement(kind)
    ax, ay = pl.anchor
    t = QTransform()
    # Order (Qt applies right-to-left): scale * xscale * rotate * translate(-anchor)
    t.scale(_PX_PER_PT * pl.xscale, _PX_PER_PT * pl.yscale)
    if pl.rotate_deg:
        t.rotate(pl.rotate_deg)
    t.translate(-ax, -ay)
    return t


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SymbolPath:
    path: QPainterPath          # already in local pixel coordinates
    stroke_width: float         # raw SVG stroke width (pt); thin ~0.4, thick ~0.8
    filled: bool                # True if the path should be filled (closed body)


# SVG stroke widths cluster around 0.3985 pt (thin) and 0.797 pt (thick).
_THICK_THRESHOLD = 0.6


def is_thick(stroke_width: float) -> bool:
    return stroke_width >= _THICK_THRESHOLD


@lru_cache(maxsize=None)
def symbol_paths(kind: str) -> tuple[SymbolPath, ...]:
    """
    Return the painter paths for *kind*, transformed into local pixel space.

    Reads only the manifest (no ``.svg`` access).  Each entry has two geometry
    lists, both mapped through the component's :func:`_local_transform`:

    * ``paths`` — body geometry.  Each path's stroke width is preserved (raw SVG
      pt) so the item maps thin strokes to ``LINE_W`` and thick to ``LINE_W*2``
      (§5.2).  **Fill rule:** a path is *filled* unless its fill is the explicit
      ``none``.  dvisvgm emits a solid body (diode triangle, transistor/LED
      arrowheads) as a bare ``<path>`` (no fill attribute = SVG default black
      fill); the export records that as ``#000`` (see
      ``tools/export_circuitikz_svgs.py``).
    * ``glyphs`` — text marks (``+``/``−``) pre-resolved by the export into a
      path ``d`` plus a baked affine ``matrix``; each is painted as a filled
      body via ``QTransform(*matrix)`` then the component transform.
    """
    key = manifest_key(kind)
    if key not in _manifest():
        return ()
    entry = _manifest()[key]
    xform = _local_transform(kind)

    out: list[SymbolPath] = []
    for p in entry["paths"]:
        local = xform.map(parse_path(p["d"]))
        # A bare path (default/solid fill) is a filled body; only an explicit
        # ``fill='none'`` is stroked-only.
        filled = p.get("fill", "none").lower() != "none"
        out.append(SymbolPath(path=local, stroke_width=float(p["stroke_width"]), filled=filled))

    for g in entry.get("glyphs", ()):
        placed = xform.map(QTransform(*g["matrix"]).map(parse_path(g["d"])))
        out.append(SymbolPath(path=placed, stroke_width=float(g["stroke_width"]), filled=True))

    return tuple(out)
