"""
SVG-symbol translation layer for canvas painting.

Component symbols are *not* hand-coded.  They are derived from the CircuiTikZ
SVG exports collected in ``tools/circuitikz_svgs/manifest.json`` (generated by
``tools/export_circuitikz_svgs.sh`` with the ``[american]`` option).

This module:

  * loads and caches the manifest,
  * parses each path ``d`` string into a :class:`QPainterPath`
    (supporting the ``M / L / H / V / C / S / Q / Z`` commands emitted by
    ``dvisvgm``),
  * applies a per-component affine transform that maps the SVG point
    coordinate space into the component's *local* pixel space (origin at the
    component origin pin, scaled by ``GRID_PX``) so the painted symbol lines up
    with the :class:`~app.components.model.PinDef` offsets in the registry.

The mapping from SVG path command to ``QPainterPath`` call follows §5.2 of the
spec:

    M x y              -> path.moveTo(x, y)
    L x y              -> path.lineTo(x, y)
    H x                -> path.lineTo(x, currentY)
    V y                -> path.lineTo(currentX, y)
    C x1 y1 x2 y2 x y  -> path.cubicTo(x1, y1, x2, y2, x, y)
    Z                  -> path.closeSubpath()

``dvisvgm`` may additionally emit ``S`` (smooth cubic) — used by the inductor
humps — and (rarely) ``Q`` (quadratic); both are handled here.

The SVG y-axis matches Qt's (y increases downward), so no axis flip is needed.
"""

from __future__ import annotations

import json
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from PySide6.QtCore import QPointF
from PySide6.QtGui import QPainterPath, QTransform

from app.canvas.style import GRID_PX, MANIFEST_PATH, SVG_PT_PER_GU

# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def _manifest() -> dict:
    """Load and cache the SVG manifest as a dict keyed by node name."""
    with open(MANIFEST_PATH, encoding="utf-8") as fh:
        return json.load(fh)


# Registry ``kind`` -> manifest key.  Most kinds match the CircuiTikZ keyword
# verbatim; only "op amp" differs (the export script sanitises the space).
_KIND_TO_MANIFEST: dict[str, str] = {
    "op amp": "op_amp",
}


def manifest_key(kind: str) -> str:
    return _KIND_TO_MANIFEST.get(kind, kind)


# ---------------------------------------------------------------------------
# Path-string parsing
# ---------------------------------------------------------------------------

# A ``d`` string is "real" geometry only if it begins with a path command.
# dvisvgm also emits ``<use>`` glyph references whose serialised ``d`` looks
# like "g1-43" / "g0-0" (the +/- symbols inside source bodies); those carry no
# stroke geometry and are skipped — the corresponding text glyphs are drawn
# separately by the item classes.
_CMD_RE = re.compile(r"[MLHVCSQTZ]|[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?")
_IS_PATH_RE = re.compile(r"^\s*[Mm]")


def is_geometry(d: str) -> bool:
    """True if *d* is a real path (not a glyph-reference placeholder)."""
    return bool(_IS_PATH_RE.match(d))


def parse_path(d: str) -> QPainterPath:
    """
    Translate an SVG path ``d`` string into a :class:`QPainterPath`.

    Only the absolute-coordinate commands produced by ``dvisvgm`` are handled
    (``M L H V C S Q Z``).  Coordinates are left in SVG point units; callers
    apply the local-space transform separately.
    """
    path = QPainterPath()
    tokens = _CMD_RE.findall(d)
    j = 0
    cmd: str | None = None
    cx = cy = 0.0
    # Tracking last cubic control point for the smooth-curve (``S``) reflection.
    last_c2x = last_c2y = None  # type: ignore[assignment]

    def _f(idx: int) -> float:
        return float(tokens[idx])

    while j < len(tokens):
        tok = tokens[j]
        if tok in "MLHVCSQTZ":
            cmd = tok
            j += 1
            if cmd == "Z":
                path.closeSubpath()
                cmd = None
                last_c2x = last_c2y = None
                continue
        if cmd is None:
            j += 1
            continue

        if cmd == "M":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.moveTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "L":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "H":
            cx = _f(j)
            j += 1
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "V":
            cy = _f(j)
            j += 1
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "C":
            x1, y1, x2, y2, x, y = (_f(j + k) for k in range(6))
            j += 6
            path.cubicTo(x1, y1, x2, y2, x, y)
            cx, cy = x, y
            last_c2x, last_c2y = x2, y2
        elif cmd == "S":
            # Smooth cubic: first control point is the reflection of the
            # previous curve's second control point about the current point.
            x2, y2, x, y = (_f(j + k) for k in range(4))
            j += 4
            if last_c2x is None:
                x1, y1 = cx, cy
            else:
                x1, y1 = 2 * cx - last_c2x, 2 * cy - last_c2y
            path.cubicTo(x1, y1, x2, y2, x, y)
            cx, cy = x, y
            last_c2x, last_c2y = x2, y2
        elif cmd == "Q":
            x1, y1, x, y = (_f(j + k) for k in range(4))
            j += 4
            path.quadTo(x1, y1, x, y)
            cx, cy = x, y
            last_c2x = last_c2y = None
        elif cmd == "T":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        else:  # pragma: no cover - defensive
            j += 1

    return path


# ---------------------------------------------------------------------------
# Per-component placement transform
# ---------------------------------------------------------------------------
#
# Every export shares one uniform scale: the bipole terminal span of
# 56.6953 pt corresponds to exactly 2 GU, i.e. SVG_PT_PER_GU = 28.34765.
# A component's symbol is placed by:
#
#   1. translating the SVG anchor point to the local origin,
#   2. optionally rotating 90 deg (the source bodies are drawn horizontally in
#      the SVG but stand vertically in the registry),
#   3. scaling SVG points to local pixels  (GRID_PX / SVG_PT_PER_GU).
#
# ``Placement`` records the SVG anchor (which SVG point becomes local (0,0))
# and the rotation in degrees applied about that anchor.

_PX_PER_PT = GRID_PX / SVG_PT_PER_GU

# Bipole terminal x-coordinates in the SVG (constant across all bipoles).
_BIPOLE_IN_X = -69.808597
_BIPOLE_OUT_X = -13.1133


@dataclass(frozen=True)
class Placement:
    anchor: tuple[float, float]  # SVG point mapped to local (0, 0)
    rotate_deg: float = 0.0      # rotation about the anchor, applied after translate
    xscale: float = 1.0          # horizontal scale applied to symbol paths only
    yscale: float = 1.0          # vertical scale applied to symbol paths only
                                 # xscale/yscale correct CTikZ internal geometry
                                 # mismatches; they do not move pin positions.
                                 # See §5.5 of PROJECT_SPEC.md for the procedure.


# Horizontal two-terminal devices: lead axis y read from the manifest at load
# time (it differs per component).  ``in`` pin = SVG (_BIPOLE_IN_X, lead_y).
_HORIZONTAL_BIPOLES = {"R", "C", "L", "D", "zD", "sD", "tD", "zzD", "leD"}

# Vertical sources: the SVG draws them horizontally; rotate +90 deg so the
# SVG +x axis becomes local +y (registry pins at (0,0) and (0,2)).
_VERTICAL_SOURCES = {"V", "I", "vsourcesin", "isourcesin", "cV", "cI"}

# Multi-terminal anchors are taken directly from the SVG terminal points.
_MULTI_ANCHORS: dict[str, Placement] = {
    # These SVGs are exported with explicit grid-aligned terminal leads (see
    # tools/export_circuitikz_svgs.sh -> TRIPOLE_LEADS), so every terminal sits
    # on the registry pin grid with no run-time bridging needed.  The anchor is
    # simply the SVG point that maps to the component's local origin.
    #
    # op amp: origin = node center.  Terminals (grid units, Qt y-down) are then
    # + (-1.5,+0.5), - (-1.5,-0.5), out (1.5,0).  Power supply pins omitted.
    "op amp": Placement(anchor=(-19.3183, -33.8613)),
    # Ground / reference node symbols: origin = connection pin at the top.
    # Anchor = SVG coordinate of the first point of the vertical lead (the
    # connection point at circuit (0,0)).  Symbol extends downward in local space.
    "ground":  Placement(anchor=(-63.65625, -69.808597)),
    "rground": Placement(anchor=(-63.65625, -69.808597)),
    "sground": Placement(anchor=(-63.65625, -69.808597)),
    "nground": Placement(anchor=(-60.679687, -69.808597)),
    "pground": Placement(anchor=(-60.679687, -69.609374)),
    "cground": Placement(anchor=(-59.687499, -69.808597)),
    "eground": Placement(anchor=(-58.894533, -69.808597)),
    # Power rails: vcc/vdd point up (pin at bottom of stem), vee/vss point down (pin at top).
    # Anchor = SVG coordinate of the stem endpoint that is the connection pin.
    "vcc": Placement(anchor=(-65.640623, -54.132812)),
    "vdd": Placement(anchor=(-65.640623, -54.132812)),
    "vee": Placement(anchor=(-65.640623, -69.808597)),
    "vss": Placement(anchor=(-65.640623, -69.808597)),

    # npn / pnp: origin = base terminal (endpoint of the base lead stub).
    # SVG base terminal measured from re-exported manifest: (-61.8398, -33.492188).
    # Collector/emitter sit at (1.013, ±1.0) GU from base; 0.013 GU x-error is
    # sub-pixel (~0.8 px) so no xscale correction is applied.
    "npn": Placement(anchor=(-61.8398, -33.492188)),
    "pnp": Placement(anchor=(-61.8398, -33.492188)),

    # nigfete / nigfetd: origin = gate terminal (end of the gate lead).
    # Terminals: drain (1.0,-1), source (1.0,+0.5), gate (0,0).
    # xscale=1.0167 stretches the body so drain/source x aligns with the
    # 1.0 GU registry pin (CTikZ internal x = 0.9836 GU; 0.9836×1.0167≈1.0).
    "nigfete": Placement(anchor=(-61.7422, -32.14453), xscale=1.0167),
    "nigfetd": Placement(anchor=(-61.7422, -32.14453), xscale=1.0167),
    # bodydiode variants share the same gate anchor; body diode extends rightward.
    "nigfete_bodydiode": Placement(anchor=(-61.7422, -32.14453), xscale=1.0167),
    "nigfetd_bodydiode": Placement(anchor=(-61.7422, -32.14453), xscale=1.0167),

    # pigfete / pigfetd: same x geometry as nigfete but gate is higher (y-mirrored).
    # Terminals: source (1.0,-0.5), drain (1.0,+1.0), gate (0,0).
    "pigfete": Placement(anchor=(-61.7422, -47.48047), xscale=1.0167),
    "pigfetd": Placement(anchor=(-61.7422, -47.48047), xscale=1.0167),
    "pigfete_bodydiode": Placement(anchor=(-61.7422, -47.48047), xscale=1.0167),
    "pigfetd_bodydiode": Placement(anchor=(-61.7422, -47.48047), xscale=1.0167),
}


def _lead_y(key: str) -> float:
    """Read the y of a horizontal bipole's lead axis from its first lead path."""
    for p in _manifest()[key]["paths"]:
        d = p["d"]
        mobj = re.match(r"^M(-?[\d.]+)(-?[\d.]+)", d)
        if mobj and abs(float(mobj.group(1)) - _BIPOLE_IN_X) < 0.5:
            return float(mobj.group(2))
    raise ValueError(f"no lead path found for {key!r}")


def _placement(kind: str) -> Placement:
    # Filled variants (e.g. "zD*") share geometry with their base kind ("zD").
    base = kind[:-1] if kind.endswith("*") else kind
    key = manifest_key(kind)
    if base in _HORIZONTAL_BIPOLES:
        return Placement(anchor=(_BIPOLE_IN_X, _lead_y(key)))
    if base in _VERTICAL_SOURCES:
        return Placement(anchor=(_BIPOLE_IN_X, _lead_y(key)), rotate_deg=90.0)
    if base in _MULTI_ANCHORS:
        return _MULTI_ANCHORS[base]
    raise KeyError(f"no placement defined for kind {kind!r}")


@lru_cache(maxsize=None)
def _local_transform(kind: str) -> QTransform:
    """
    Affine transform mapping SVG point coordinates to local pixel coordinates
    (origin at the component origin pin, scaled by GRID_PX).
    """
    pl = _placement(kind)
    ax, ay = pl.anchor
    t = QTransform()
    # Order (Qt applies right-to-left): scale * xscale * rotate * translate(-anchor)
    t.scale(_PX_PER_PT * pl.xscale, _PX_PER_PT * pl.yscale)
    if pl.rotate_deg:
        t.rotate(pl.rotate_deg)
    t.translate(-ax, -ay)
    return t


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SymbolPath:
    path: QPainterPath          # already in local pixel coordinates
    stroke_width: float         # raw SVG stroke width (pt); thin ~0.4, thick ~0.8
    filled: bool                # True if the path should be filled (closed body)


# SVG stroke widths cluster around 0.3985 pt (thin) and 0.797 pt (thick).
_THICK_THRESHOLD = 0.6


def is_thick(stroke_width: float) -> bool:
    return stroke_width >= _THICK_THRESHOLD


# ---------------------------------------------------------------------------
# Glyph (<use>) resolution from the raw source SVGs
# ---------------------------------------------------------------------------
#
# The manifest records only the stroked/filled <path> geometry.  Text marks
# such as the + / - of a voltage source are emitted by dvisvgm as <use>
# references to glyph paths in <defs>; the manifest collapses these to opaque
# placeholders ("g1-43").  To reproduce them pixel-accurately we read the
# original .svg, resolve each <use> against its <defs> glyph, and compose:
#
#     effective = group_matrix * translate(use.x, use.y) * glyph_path
#
# The composed glyph path is then mapped into local pixel space with the same
# component transform used for the manifest paths, and treated as a filled body
# (glyph outlines are closed regions).

_SVG_DIRS = ("nodes", "bipoles", "tripoles")
_MATRIX_RE = re.compile(
    r"matrix\(\s*([-\d.eE]+)\s+([-\d.eE]+)\s+([-\d.eE]+)\s+"
    r"([-\d.eE]+)\s+([-\d.eE]+)\s+([-\d.eE]+)\s*\)"
)


@lru_cache(maxsize=1)
def _svg_root_dir() -> Path:
    return Path(MANIFEST_PATH).resolve().parent


def _source_svg_path(kind: str) -> Path | None:
    key = manifest_key(kind)
    root = _svg_root_dir()
    for sub in _SVG_DIRS:
        cand = root / sub / f"{key}.svg"
        if cand.exists():
            return cand
    return None


def _glyph_transform(matrix_str: str | None, use_x: float, use_y: float) -> QTransform:
    """Compose group matrix * translate(use_x, use_y)."""
    t = QTransform()
    if matrix_str:
        m = _MATRIX_RE.search(matrix_str)
        if m:
            a, b, c, d, e, f = (float(v) for v in m.groups())
            # QTransform(m11,m12,m21,m22,dx,dy) maps (x,y)->(a x + c y + e, b x + d y + f)
            t = QTransform(a, b, c, d, e, f)
    t.translate(use_x, use_y)
    return t


@lru_cache(maxsize=None)
def _glyph_paths(kind: str) -> tuple[SymbolPath, ...]:
    """Resolve <use> glyph references in the source SVG into filled paths
    (local pixel space).  Returns empty if the SVG has no glyph refs."""
    svg = _source_svg_path(kind)
    if svg is None:
        return ()
    try:
        tree = ET.parse(svg)
    except ET.ParseError:  # pragma: no cover - defensive
        return ()
    root = tree.getroot()

    def _tag(el: ET.Element) -> str:
        return el.tag.rsplit("}", 1)[-1]

    HREF = "{http://www.w3.org/1999/xlink}href"

    # Collect <defs> glyph path geometry by id.
    glyph_defs: dict[str, str] = {}
    for el in root.iter():
        if _tag(el) == "path" and el.get("id"):
            glyph_defs[el.get("id")] = el.get("d", "")

    if not glyph_defs:
        return ()

    xform = _local_transform(kind)
    out: list[SymbolPath] = []

    # Walk groups so we can read each <use>'s enclosing transform matrix.
    def _walk(el: ET.Element, inherited: str | None) -> None:
        for child in el:
            tag = _tag(child)
            if tag == "g":
                _walk(child, child.get("transform", inherited))
            elif tag == "use":
                ref = (child.get(HREF) or child.get("href") or "").lstrip("#")
                d = glyph_defs.get(ref)
                if not d:
                    continue
                ux = float(child.get("x", "0"))
                uy = float(child.get("y", "0"))
                gtf = _glyph_transform(child.get("transform", inherited), ux, uy)
                raw = parse_path(d)
                placed = xform.map(gtf.map(raw))
                out.append(SymbolPath(path=placed, stroke_width=0.3985, filled=True))

    _walk(root, None)
    return tuple(out)


@lru_cache(maxsize=None)
def symbol_paths(kind: str) -> tuple[SymbolPath, ...]:
    """
    Return the painter paths for *kind*, transformed into local pixel space.

    Each path's stroke width is preserved (raw SVG pt) so the item can map thin
    strokes to ``LINE_W`` and thick strokes to ``LINE_W * 2`` per §5.2.

    Fill rule (§5.2): a path is filled only when its ``fill`` attribute is
    absent or ``#000``; ``fill='none'`` paths are stroked only.  In practice the
    CircuiTikZ exports set ``fill='none'`` on every path and convey solid bodies
    (diode triangle, arrowheads) via *closed* subpaths.  We therefore treat a
    path as filled when it contains a ``Z`` close command, which matches the
    intended visual result.
    """
    key = manifest_key(kind)
    if key not in _manifest():
        return ()
    entry = _manifest()[key]
    xform = _local_transform(kind)

    out: list[SymbolPath] = []
    for p in entry["paths"]:
        d = p["d"]
        if not is_geometry(d):
            continue
        raw = parse_path(d)
        local = xform.map(raw)
        fill_attr = p.get("fill", "none").lower()
        if fill_attr == "":
            # Absent fill attribute in original SVG = SVG default black fill.
            filled = True
        elif fill_attr in ("#000", "#000000", "black"):
            filled = "z" in d.lower()
        else:
            filled = False
        out.append(
            SymbolPath(
                path=local,
                stroke_width=float(p["stroke_width"]),
                filled=filled,
            )
        )

    # Append resolved glyph marks (+/- etc.) from the source SVG, if any.
    out.extend(_glyph_paths(kind))
    return tuple(out)
