"""
SVG-symbol translation layer for canvas painting.

Component symbols are *not* hand-coded.  They are derived from the CircuiTikZ
SVG exports compiled into the **self-contained** geometry
``components/geometry.json`` (generated by
``components/generate_components.py``).  This module reads **only** the geometry —
it never touches the ``.svg`` files at run time.

Each geometry entry carries two geometry lists (both in SVG point coordinates):

  * ``paths``  — the stroked/filled body geometry; and
  * ``glyphs`` — text marks (the ``+``/``−`` of sources) pre-resolved from the
    SVG's ``<use>``/``<defs>`` indirection into a path ``d`` plus a baked affine
    ``matrix``.

This module:

  * loads and caches the geometry,
  * parses each path ``d`` string into a :class:`QPainterPath`
    (supporting the ``M / L / H / V / C / S / Q / Z`` commands emitted by
    ``dvisvgm``),
  * applies a per-component affine transform that maps the SVG point
    coordinate space into the component's *local* pixel space (origin at the
    component origin pin, scaled by ``GRID_PX``) so the painted symbol lines up
    with the :class:`~app.components.model.PinDef` offsets in the registry.

The mapping from SVG path command to ``QPainterPath`` call follows §5.2 of the
spec:

    M x y              -> path.moveTo(x, y)
    L x y              -> path.lineTo(x, y)
    H x                -> path.lineTo(x, currentY)
    V y                -> path.lineTo(currentX, y)
    C x1 y1 x2 y2 x y  -> path.cubicTo(x1, y1, x2, y2, x, y)
    Z                  -> path.closeSubpath()

``dvisvgm`` may additionally emit ``S`` (smooth cubic) — used by the inductor
humps — and (rarely) ``Q`` (quadratic); both are handled here.

The SVG y-axis matches Qt's (y increases downward), so no axis flip is needed.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache

from PySide6.QtGui import QPainterPath, QTransform

from app.canvas.style import GRID_PX, GEOMETRY_PATH, SVG_PT_PER_GU
from app.components import library

# ---------------------------------------------------------------------------
# Geometry loading
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def _geometry() -> dict:
    """Load and cache the SVG geometry as a dict keyed by node name."""
    with open(GEOMETRY_PATH, encoding="utf-8") as fh:
        return json.load(fh)


# Registry ``kind`` -> geometry key.  Canonical definition lives in the Qt-free
# component library (``library.geometry_key``); re-exported here under the same
# public name for the canvas and its tests.
geometry_key = library.geometry_key


# ---------------------------------------------------------------------------
# Path-string parsing
# ---------------------------------------------------------------------------

_CMD_RE = re.compile(r"[MLHVCSQTZ]|[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?")


def parse_path(d: str) -> QPainterPath:
    """
    Translate an SVG path ``d`` string into a :class:`QPainterPath`.

    Only the absolute-coordinate commands produced by ``dvisvgm`` are handled
    (``M L H V C S Q Z``).  Coordinates are left in SVG point units; callers
    apply the local-space transform separately.
    """
    path = QPainterPath()
    tokens = _CMD_RE.findall(d)
    j = 0
    cmd: str | None = None
    cx = cy = 0.0
    # Tracking last cubic control point for the smooth-curve (``S``) reflection.
    last_c2x = last_c2y = None  # type: ignore[assignment]

    def _f(idx: int) -> float:
        return float(tokens[idx])

    while j < len(tokens):
        tok = tokens[j]
        if tok in "MLHVCSQTZ":
            cmd = tok
            j += 1
            if cmd == "Z":
                path.closeSubpath()
                cmd = None
                last_c2x = last_c2y = None
                continue
        if cmd is None:
            j += 1
            continue

        if cmd == "M":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.moveTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "L":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "H":
            cx = _f(j)
            j += 1
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "V":
            cy = _f(j)
            j += 1
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        elif cmd == "C":
            x1, y1, x2, y2, x, y = (_f(j + k) for k in range(6))
            j += 6
            path.cubicTo(x1, y1, x2, y2, x, y)
            cx, cy = x, y
            last_c2x, last_c2y = x2, y2
        elif cmd == "S":
            # Smooth cubic: first control point is the reflection of the
            # previous curve's second control point about the current point.
            x2, y2, x, y = (_f(j + k) for k in range(4))
            j += 4
            if last_c2x is None:
                x1, y1 = cx, cy
            else:
                x1, y1 = 2 * cx - last_c2x, 2 * cy - last_c2y
            path.cubicTo(x1, y1, x2, y2, x, y)
            cx, cy = x, y
            last_c2x, last_c2y = x2, y2
        elif cmd == "Q":
            x1, y1, x, y = (_f(j + k) for k in range(4))
            j += 4
            path.quadTo(x1, y1, x, y)
            cx, cy = x, y
            last_c2x = last_c2y = None
        elif cmd == "T":
            cx, cy = _f(j), _f(j + 1)
            j += 2
            path.lineTo(cx, cy)
            last_c2x = last_c2y = None
        else:  # pragma: no cover - defensive
            j += 1

    return path


# ---------------------------------------------------------------------------
# Placement transform
# ---------------------------------------------------------------------------
#
# Every symbol is rendered (components/generate_components.py) inside a fixed bounding
# box with its origin pin at TeX (0,0) and short leads bridging every other pin
# to its registry grid offset.  So a single constant SVG point — the library's
# ``origin_svg`` — maps to the component's local origin for ALL kinds, and the
# placement is a pure translate-then-uniform-scale: no per-component anchors,
# rotation, or scale corrections (the leads put every pin on the grid).

_PX_PER_PT = GRID_PX / SVG_PT_PER_GU


def local_transform() -> QTransform:
    """Affine map from SVG point coordinates to local pixel coordinates.

    Computed fresh from the library's ``origin_svg`` on every call, so callers
    that may reload the component store (the component editor) always see the
    current origin.  The canvas hot path uses the cached :func:`_local_transform`.
    """
    ox, oy = library.origin_svg()
    t = QTransform()
    # Qt applies right-to-left: scale ∘ translate(-origin).
    t.scale(_PX_PER_PT, _PX_PER_PT)
    t.translate(-ox, -oy)
    return t


@lru_cache(maxsize=1)
def _local_transform() -> QTransform:
    """Cached :func:`local_transform` (the origin is a bundled constant)."""
    return local_transform()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SymbolPath:
    path: QPainterPath          # already in local pixel coordinates
    stroke_width: float         # raw SVG stroke width (pt); thin ~0.4, thick ~0.8
    filled: bool                # True if the path should be filled (closed body)


# SVG stroke widths cluster around 0.3985 pt (thin) and 0.797 pt (thick).
_THICK_THRESHOLD = 0.6


def is_thick(stroke_width: float) -> bool:
    return stroke_width >= _THICK_THRESHOLD


@lru_cache(maxsize=None)
def symbol_paths(kind: str) -> tuple[SymbolPath, ...]:
    """
    Return the painter paths for *kind*, transformed into local pixel space.

    Reads only the geometry (no ``.svg`` access).  Each entry has two geometry
    lists, both mapped through the component's :func:`_local_transform`:

    * ``paths`` — body geometry.  Each path's stroke width is preserved (raw SVG
      pt) so the item maps thin strokes to ``LINE_W`` and thick to ``LINE_W*2``
      (§5.2).  **Fill rule:** a path is *filled* unless its fill is the explicit
      ``none``.  dvisvgm emits a solid body (diode triangle, transistor/LED
      arrowheads) as a bare ``<path>`` (no fill attribute = SVG default black
      fill); the export records that as ``#000`` (see
      ``components/generate_components.py``).
    * ``glyphs`` — text marks (``+``/``−``) pre-resolved by the export into a
      path ``d`` plus a baked affine ``matrix``; each is painted as a filled
      body via ``QTransform(*matrix)`` then the component transform.
    """
    key = geometry_key(kind)
    if key not in _geometry():
        return ()
    entry = _geometry()[key]
    xform = _local_transform()

    out: list[SymbolPath] = []
    for p in entry["paths"]:
        local = xform.map(parse_path(p["d"]))
        # A bare path (default/solid fill) is a filled body; only an explicit
        # ``fill='none'`` is stroked-only.
        filled = p.get("fill", "none").lower() != "none"
        out.append(SymbolPath(path=local, stroke_width=float(p["stroke_width"]), filled=filled))

    for g in entry.get("glyphs", ()):
        placed = xform.map(QTransform(*g["matrix"]).map(parse_path(g["d"])))
        out.append(SymbolPath(path=placed, stroke_width=float(g["stroke_width"]), filled=True))

    return tuple(out)
